### PR TITLE
[DDO-1449] Add wsmtest-sync account

### PR DESCRIPTION
**Pull request by jack-r-warren**
Adds an account to Argo CD able to sync wsmtest. I've generated a token for it and fully tested that this works, and that it rejects attempts to do anything else.

```
curl --fail --silent --show-error --location --request POST 'https://ap-argocd.dsp-devops.broadinstitute.org/api/v1/applications/workspacemanager-wsmtest/sync' \
    --header "Authorization: Bearer $(vault read -field=token secret/suitable/argocd/local-accounts/low-privileged/wsmtest-sync)" \
    | jq .operation
```

### CODE REVIEW

**Review by em-may — APPROVED** [review]
Looks simple enough, would appreciate a brief explanation of what's going on so I can better understand, thanks!

**Comment by jack-r-warren** [comment]
> Looks simple enough, would appreciate a brief explanation of what's going on so I can better understand, thanks!

Well, I don't know how fully I understand either. In theory, I'm just following [this](https://argoproj.github.io/argo-cd/operator-manual/user-management/#create-new-user) and [this](https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/). That seems simple enough except neither Mike or I are positive how non-devops people who log in with github get access, because there's not a github-team-to-argo-role binding for non-devops people in that policy.csv snippet we have.

We decided it is a good question but not really relevant for this so it can wait for tomorrow.

**Review by choover-broad — APPROVED** [review]
Looks fine!

An alternative option would be to set this permission directly in the wsmtest project ([example](https://github.com/broadinstitute/terra-helm/blob/master/charts/terra-argocd-env/templates/project.yaml#L17)): ) but that would involve some helmfile magic ([hereabouts](https://github.com/broadinstitute/terra-helmfile/blob/master/helmfile.yaml#L176)) and this is a one-off case, so this is probably better!

**Comment by jack-r-warren** [comment]
> Looks fine!
> 
> An alternative option would be to set this permission directly in the wsmtest project ([example](https://github.com/broadinstitute/terra-helm/blob/master/charts/terra-argocd-env/templates/project.yaml#L17)) but that would involve some helmfile magic ([hereabouts](https://github.com/broadinstitute/terra-helmfile/blob/master/helmfile.yaml#L176)) and this is a one-off case, so your approach here is probably better!

Mm that's good to know, if we get a bunch of requests for this sorta thing maybe that's the way we build this out

**Pull request merged**
