### PR TITLE
DDO-915 Automatically reset all Terra ArgoCD Apps back to master branch of terra-helmfile every night

### PR DESCRIPTION
**Pull request by choover-broad**
* Configure ArgoCD apps to deploy HEAD revision of terra-helmfile by default (previously this was not specified)
* Add a sync window + automated sync policy to terra-app-generator to automatically sync during a 10-minute window every night at 10pm (the nightly perf deploy kicks off at

### CODE REVIEW

**Comment by gmalkov** [comment]
Will this apply just to perf or to all apps in all envs? We don't want peronal env apps set to custom branches resetting every night, right?

**Comment by choover-broad** [comment]
@gmalkov does anyone actually use ArgoCD to deploy to personal envs?

**Comment by choover-broad** [comment]
It's all envs, I can add a config switch to exclude personal envs, though. Just means a bit more complexity in terra-helmfile

**Comment by gmalkov** [comment]
> @gmalkov does anyone actually use ArgoCD to deploy to personal envs?

I do sometimes. Dunno if anyone else does. I guess we can encourage use of tools like Skaffold for that use case instead.

**Review by gmalkov — APPROVED** [review]

**Pull request merged**
